##########################################################
##########################################################
###                                                    ###
###      Config file for runing iKAT experiments       ###
###                                                    ###
##########################################################
##########################################################

iterate:

# rewrites choices
  # P -> personalize, D -> demo, C -> cot, Re -> rel explain
  # O -> oracle, Rf -> rel feedback

  #retrieval_query_types=("raw" "rar_rw" "rar_rwrs" "oracle_utterance" "raw_llm_rm_P__Re___" "raw_llm_rm____Re___" "rar_ptkb_sum_cot0_rw" "rar_ptkb_sum_cot0_rwrs" "rar_ptkb_sum_rw" "rar_ptkb_sum_rwrs")
  #reranking_query_types=("raw" "rar_rw" "rar_rwrs" "oracle_utterance" "rar_ptkb_sum_cot0_rw" "rar_ptkb_sum_cot0_rwrs" "rar_ptkb_sum_rw" "rar_ptkb_sum_rwrs" "raw_llm_rm_P__Re___" "raw_llm_rm____Re___")
  #reranking_query_types=("raw" "rar_rw" "rar_rwrs" "oracle_utterance" "rar_ptkb_sum_cot0_rw" "rar_ptkb_sum_cot0_rwrs" "rar_ptkb_sum_rw" "rar_ptkb_sum_rwrs" "raw_llm_rm_P__Re___" "raw_llm_rm____Re___")
  #reranking_query_types=("rar_ptkb_sum_cot0_rwrs" "rar_ptkb_sum_rwrs" "raw_llm_rm_P__Re___" "raw_llm_rm____Re___")
  # reranking_query_types=("rar_ptkb_sum_cot0_rwrs" "rar_ptkb_sum_rwrs")
  #retrieval_query_types=("raw" "rar_rw" "rar_rwrs" "oracle_utterance" "raw_llm_rm_P__Re___" "raw_llm_rm____Re___" "rar_ptkb_sum_cot0_rw" "rar_ptkb_sum_cot0_rwrs" "rar_ptkb_sum_rw" "rar_ptkb_sum_rwrs")
  #retrieval_query_types=("rar_personalized_cot1_rw" "rar_personalized_cotN_rw")
  #retrieval_query_types=("rar_rw_fuse_rar_personcot1_rw")
  # retrieval_query_types=("rar_rw_fuse_rar_rwrs")
  # reranking_query_types=("rar_personalized_cot1_rw")
  #retrieval_query_types=("gpt-4o_rar_rw" "gpt-4o_rar_rwrs" "gpt-4o_rar_personalized_cot1_rw")
  #retrieval_query_types=("gpt-4o_rar_rw_fuse_rar_rwrs_fuse_manual_depersonalized_cot1_rw")
  #retrieval_query_types=("gpt-4o_rar_rwrs_fuse_personalized_cot1_rw") 
  #retrieval_query_types=("round_robin_gpt-4o_3_lists")
  #retrieval_query_types=("personalize_level_3_lists_tune") 
  #retrieval_query_types=("gpt-4o_rar_rw" "gpt-4o_rar_rwrs" "gpt-4o_rar_personalized_cot1_rw")
  #retrieval_query_types=("gpt-4o_judge_and_rewrite_optimize_mrr_non_normalize_test")

  retrieval_query_type: ["raw", "oracle"]

fixed:
  ###############################################
  ## General
  ###############################################
  collection: "ClueWeb_ikat"  # Dataset collection
  topics: "ikat_23_test"  # Test topics
  input_query_path: "../../data/topics/ikat23/ikat_2023_test.json"  # Path to input query file

  # use /part/02 for octal30, /part/01 for octal31
  # index_dir_path="/part/02/Tmp/yuchen/clueweb22b_ikat23_fengran_sparse_index_2/" # Please use local disk index to achieve the fastest access
  sparse_index_dir_path: "/part/01/Tmp/yuchen/indexes/clueweb22b_ikat23_official_sparse_index/"  # Use local disk index for fastest access
  output_dir_path: "../../results"  # Path to save results
  qrel_file_path: "../../data/qrels/ikat_23_qrel.txt"  # Qrel file path
  seed: 42  # Random seed for reproducibility

  save_results_to_object: true
  save_ranking_list: true
  run_rag: true
  run_eval: true

  ###############################################
  ## Retrieval
  ###############################################
  retrieval_model: "BM25"  # Can be: "none", "BM25", "ance", "dpr", "splade_v3"
  retrieval_top_k: 1000  # Top K results for retrieval
  ############# Splade ############
  splade_query_encoder_path: "/data/rech/huiyuche/huggingface/models--naver--splade-v3/snapshots/8291b13eb8f4e24cc745c542825f14eb87296879"  # Splade query encoder path
  splade_index_dir_path: "/part/01/Tmp/yuchen/indexes/clueweb22b_ikat23_splade_v3"  # Splade index path
  ############# Dense (and also splade) ############
  use_pyserini_dense_search: false
  dense_query_encoder_path: "/data/rech/huiyuche/huggingface/models--castorini--ance-msmarco-passage/snapshots/6d7e7d6b6c59dd691671f280bc74edb4297f8234"  # Dense query encoder path
  dense_index_dir_path: "/part/01/Tmp/yuchen/indexes/clueweb22b_ikat23_ance_merged_2"  # Dense index path
  query_encoder_batch_size: 200  # Batch size for query encoding
  faiss_n_gpu: 4  # Number of GPUs for FAISS
  use_gpu_for_faiss: true
  embed_dim: 768  # Embedding dimension
  tempmem: -1  # Temporary memory setting
  query_gpu_id: 3  # GPU ID for query processing
  passage_block_num: 12  # Passage block number (e.g., 116 for ikat)

  ############# BM25 ############
  bm25_k1: 0.9  # BM25 k1 parameter
  bm25_b: 0.4  # BM25 b parameter
  ############# QE ############
  qe_type: "none"  # Query expansion type
  fb_terms: 20  # Feedback terms
  fb_docs: 10  # Feedback documents
  original_query_weight: 0.5  # Weight for original query

  ###############################################
  ## Fusion
  ###############################################
  fusion_type: "none"  # Fusion strategy
  QRs_to_rank: ["gpt-4o_rar_rw", "gpt-4o_rar_rwrs", "gpt-4o_judge_and_rewrite_rw"]  # Queries to rank
  fuse_weights: [0.1, 0.4]  # Weights for fusion
  fusion_normalization: "min-max"  # Fusion normalization method
  level_type: "gpt-4o_judge_and_rewrite"  # Personalization level type
  per_query_weight_max_value: 1.2  # Max weight per query
  optimize_level_weights: "no_level"  # Level weight optimization
  target_metrics: "mrr,ndcg@3"  # Target evaluation metrics
  optimize_step: 0.01  # Optimization step size

  ###############################################
  ## Reranking
  ###############################################
  reranker: "none"  # Reranker type
  rerank_top_k: 50  # Top K results for reranking
  cache_dir: "/data/rech/huiyuche/huggingface"  # Cache directory
  rerank_batch_size: 67  # Batch size for reranking
  rerank_quant: "none"  # Rerank quantization method
  rankgpt_llm: "gpt-3.5-turbo"  # GPT model for ranking
  window_size: 4  # Window size for reranking
  step: 1  # Step size for reranking

  ###############################################
  ## Response Generation
  ###############################################
  generation_model: "none"  # Generation model
  generation_prompt: "none"  # Prompt for generation
  generation_top_k: 3  # Top K generations

  ###############################################
  ## Metrics
  ###############################################
  metrics: "map,ndcg,ndcg_cut.1,ndcg_cut.3,ndcg_cut.5,ndcg_cut.10,P.1,P.3,P.5,P.10,P.20,recall.5,recall.10,recall.20,recall.50,recall.100,recall.1000,recip_rank"  # Evaluation metrics
  given_ranking_list_path: "/data/rech/huiyuche/TREC_iKAT_2024/results/ClueWeb_ikat/ikat_23_test/ranking/S1[gpt-4o_rar_rwrs_fuse_personalized_cot1_rw]-S2[none]-g[none]-[none_4_1_none]-[s2_top50].txt"  # Path to given ranking list

  ###############################################
  ## iKAT Project Specific
  ###############################################
  run_name: "none"  # Run name
  retrieval_query_type: "none"  # Query type for retrieval
  reranking_query_type: "none"  # Query type for reranking
  generation_query_type: "none"  # Query type for generation
